
FROM python:3.9

# Set the working directory to /app
WORKDIR /app


COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000


ENV NAME mqtt-publisher


CMD ["python", "app.py"]
